linters:
  disable-all: true
  enable:
    - staticcheck
    - unused
    - misspell

linters-settings:
  misspell:
    locale: US

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
  
run:
  timeout: 5m
  go: '1.22'
